apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
spec:
  routes:
    - match: Host(`storage.sachathommet.fr`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: basic-auth
          namespace: infra-ingress-traefik
  tls:
    certResolver: letsencrypt-prod
