apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-longhorn-storage

resources:
  - namespace.yaml
  - ingress-route.yaml
  - recurring-jobs.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    namespace: infra-longhorn-storage
    version: 1.9.1
    includeCRDs: true
    valuesFile: values.yaml
