apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: http-basic-auth
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: http-basic-auth
  data:
    - remoteRef:
        key: 2fb2f60e-6a20-4b81-896c-b35200f1a278
      secretKey: auth
