apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-prometheus-stack

resources:
  - namespace.yaml
  - ingress-route.yaml
  - secret.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    namespace: infra-prometheus-stack
    version: 81.2.2
    releaseName: monitoring
    includeCRDs: true
    valuesFile: values.yaml
