apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-external-secrets

resources:
  - bitwarden-certs.yaml
  - secret-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.0.0
    releaseName: external-secrets
    namespace: infra-external-secrets
    valuesInline:
      bitwarden-sdk-server:
        enabled: true
      installCRDs: true
