apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: 1.19.2
    releaseName: cert-manager
    namespace: infra-cert-manager
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true
