apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-authentik-auth

resources:
  - secret.yaml
  - ingress-route.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/groups.yaml
      - blueprints/default-outpost-override.yaml
      - blueprints/default-authentication-flow-override.yaml
      - blueprints/default-source-enrollment-write-override.yaml
      - blueprints/sources-google.yaml
      - blueprints/apps/argocd.yaml
      - blueprints/apps/grafana.yaml
      - blueprints/apps/forward-auth-domain.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    namespace: infra-authentik-auth
    version: 2025.12.4
    releaseName: authentik
    includeCRDs: true
    valuesFile: values.yaml
