apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-authentik-auth

resources:
  - secret.yaml
  - ingress-route.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/default-authentication-flow-override.yaml
      - blueprints/default-source-enrollment-write-override.yaml
      - blueprints/apps-argocd.yaml
      - blueprints/sources-google.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    namespace: infra-authentik-auth
    version: 2025.8.1
    releaseName: authentik
    includeCRDs: true
    valuesFile: values.yaml
