apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio
spec:
  routes:
    - match: Host(`sachathommet.fr`)
      kind: Rule
      services:
        - name: portfolio
          port: 3000
  tls:
    certResolver: letsencrypt-prod
